apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - devspaces-coding-models-access.yaml
  - personal-users-access.yaml
  - developer-hub-models-access.yaml
  - ai-safety-guardrails-access.yaml
  - model-evaluation-access.yaml
  - nemotron-api-key-provisioner-access.yaml
  - nemotron-api-key-provisioning.yaml
